#ifndef __PICTURE_TRANSFER_PROTOCOL_ASSOCIATION_INCLUDED_H__
#define __PICTURE_TRANSFER_PROTOCOL_ASSOCIATION_INCLUDED_H__

#define PTP_ASSOCIATION_UNDEFINED 0x0000 // Undefined Not an association
#define PTP_ASSOCIATION_GENERIC_FOLDER 0x0001 // GenericFolder Unused
#define PTP_ASSOCIATION_ALBUM 0x0002 // Album Reserved
#define PTP_ASSOCIATION_TIME_SEQUENCE 0x0003 // TimeSequence DefaultPlaybackDelta
#define PTP_ASSOCIATION_HORIZONTAL_PANORAMIC 0x0004 // HorizontalPanoramic Unused
#define PTP_ASSOCIATION_VERTICAL_PANORAMIC 0x0005 // VerticalPanoramic Unused
#define PTP_ASSOCIATION_2D_PANORAMIC 0x0006 // 2DPanoramic ImagesPerRow
#define PTP_ASSOCIATION_ANCILLARY_DATA 0x0007 // AncillaryData Undefined

#endif // __PICTURE_TRANSFER_PROTOCOL_ASSOCIATION_INCLUDED_H__
